; Special Dyslexic typos collected from the internet

::allways::always
::appearently::apparently
::athoratative::authoritative
::athority::authority
::belive::believe
::brainiack::madeupword
::caviot::caveat
::chanels::channels
::classsified::classified
::courved::curved
::defferance::deference
::defintion::definition
::dieased::diseased
::diffinition::definition
::direrection::direction
::easyiest::easiest
::empobied::embodied
::equivelnet::equivalent
::espeicially::especially
::exploitave::exploitive
::extenct::extent
::florecent::florescent
::forign::foreign
::funcionality::functionality
::futher::further
::graphiclay::graphically
::hepfull::helpful
::incapolated::encapsulated
::inperical::empirical
::ironicly::ironically
::miniscule::minuscule
::processess::process
::psudo::pseudo
::recieve::receive
::referer::referrer
::sentance::sentence
::serverity::severity
::simular::similar
::situational::situational
::stratageies::strategies
::symble::symbol
::trackted::tracked
::trapositia::madeupword
::unperceptable::imperceptible
::upsidedown::upside-down
::voule::vowel
::writting::writing
::writtings::writings
